# Copyright (c) 2024 Stéphane Bouchard <partiexplorer@gmail.com>

# Project information
site_name: Parti explorer
site_url: https://partiexplorer.github.io/
site_author: Stéphane Bouchard
site_description: >-
  Documentation des aventures de Parti explorer en camion aménagé avec tous ce qui entoure ce projet.

# Repository
repo_name: partiexplorer.github.io
repo_url: https://github.com/partiexplorer/partiexplorer.github.io

copyright: |
  &copy; 2024 <a href="https://github.com/partiexplorer" target="_blank" rel="noopener">Parti explorer</a>

# Configuration
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@partiexplorer/
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/partiexplorer
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/partiexplorer
    - icon: material/email
      link: mailto:partiexplorer@gmail.com
      name: partiexplorer@gmail.com

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
- Accueil: index.md
- Blog:
  - blog/index.md
- Projets: projets.md
- À propos: apropos.md
