# Copyright (c) 2024 Stéphane Bouchard <partiexplorer@gmail.com>

# Project information
site_name: Parti explorer
site_url: https://partiexplorer.github.io/
site_author: Stéphane Bouchard
site_description: >-
  Documentation des aventures de Parti explorer en camion aménagé avec tous ce qui entoure ce projet.

# Repository
repo_name: partiexplorer/partiexplorer.github.io
repo_url: https://github.com/partiexplorer/partiexplorer.github.io

copyright: |
  &copy; 2024 <a href="https://github.com/partiexplorer" target="_blank" rel="noopener">Parti explorer</a>

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: fr
  features:
    # - content.action.edit
    # - content.action.view
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  # font:
  #   test: Roboto
  #   code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    # edit: material/pencil
    # view: material/eye


# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: datetime
      timezone: America/Montreal
      locale: fr
      enable_creation_date: true
      # exclude:
      #   - index.md
  - git-committers:
      enabled: !ENV [CI, false]
      repository: partiexplorer/partiexplorer.github.io
      branch: main
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - glightbox

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@partiexplorer/
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/partiexplorer
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/partiexplorer
    - icon: material/email
      link: mailto:partiexplorer@gmail.com
      name: partiexplorer@gmail.com

extra_javascript:
  - /assets/leaflet.js
  - /assets/leaflet-gpx.js
  - /assets/leaflet.fullscreen.min.js

extra_css:
  - /stylesheets/extra.css
  - /assets/leaflet.css
  - /assets/leaflet.fullscreen.css

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

# Page tree
nav:
- Accueil: index.md
- Blog:
  - blog/index.md
- Périples:
  - Route 138: voyages/route138.md
  - Eeyou Itchee Baie-James:
    - Direction Nord: voyages/baie-james-etape-1.md
    - Immensité de la nature: voyages/baie-james-etape-2.md
    - Retour en douceur: voyages/baie-james-etape-3.md
  - Sentiers Trans-Québec Trail: voyages/tqt.md
- Projets:
  - Voyager en camion: projets/voyager-en-camion.md
  - Véhicules: projets/vehicules.md
  - Technologies: projets/techno.md
  - Impression 3D: projets/3dprint.md
- À propos: apropos.md
